Add Solidus extension metadata to gemspec
Used by GitHub Changelog Generator, among others.

Fixes the following error when running `bin/rake -T`

```
solidus_frontend 16:12:24 $ bin/rake -T
rake aborted!
NoMethodError: undefined method `gsub' for nil:NilClass
/home/gsmendoza/repos/gsmendoza/solidus_frontend/Rakefile:4:in `<top (required)>'
```